spring:
  application:
    name: ribbon-client
server:
  port: 9292
catalog-service-lb:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:3232,localhost:3333
    ServerListRefreshInterval: 15000

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"