spring:
  application:
    name: client-discovery-first
  profiles:
    active: local
  cloud:
    config:
      fail-fast: true
      server:
        git:
          uri: https://github.com/vatsank/spring-config-server.git
      retry:
        max-attempts: 20
        max-interval: 15000
        initial-interval: 10000
      discovery:
        enabled: true
        service-id: config-server
server:
  port: 8764

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka




