feign:
    hystrix:
        enabled: true
    client:
       config:
          default:
            connectTimeout: 160000000
            readTimeout: 160000000
            
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        

hystrix:
  command:
    MyTourClient#findAll():
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false
#
#
