 
 
 server:
  port: 6767

  servlet:
    context-path: /api/v1

 spring:
  application:
    name: image-service
# cloud:
#    config:
#      uri:
#      - http://localhost:1010
# 
# eureka:
#  instance:
#    instance-id: payment-service:44
#   
